### ISSUE TITLE
Check if response stream is closed

### ISSUE THREAD

**Issue by Domanser** [msmolka/ZNetCS.AspNetCore.Compression#1]
Hello.

In CompressionMiddleware.Invoke(), we have:

```
await this.next.Invoke(context);
...
bufferedStream.Seek(0, SeekOrigin.Begin);
```

But in case if some middleware closed response stream (bufferedStream refers to it), we get an exception. For example, such problem occurs when using ZNetCS.AspNetCore.Compression with Swashbuckle.AspNetCore (stream is closed in method [RespondWithSwaggerJson()](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerMiddleware.cs)). 

Such problem can be solved by adding url to CompressionOptions.IgnoredPaths, or by reordering middlewares. But maybe is it better to add checks for bufferedStream.CanSeek and bufferedStream.CanRead in CompressionMiddleware.Invoke(), before bufferedStream.Seek()?

**Comment by msmolka** [comment]
@Domanser Buffered Stream has to be moved to position 0, because otherwise there will be nothing to send to the client. The check will only hide the error, and user will be confused why there is no response. 

The compression middleware should be added at the beginning. Because buffered stream is one replaced.
I can see in code that Swagger is closing `StreamWriter` over `response.Body`. It is not feeling right because class should only close its own resources not external one. 

I have feeling that this is against idea of middleware. Because in that case no other middleware can access response body. And this body should be accessible until stared sending to client. Because in that case response cannot be compressed. 

Getting to bottom it is rather bug in Swagger, the should not close the body stream. or use `leaveOpen` parameter of `StreamWriter` constructor.

Again, there is really no way to check if it can be compressed before running middleware. And after that user has to know what is happening in code. using `CanSeek` will hide error and return nothing. So my opinion it is  better to throw exception, when something wrong happened.

The only thing I can add is to throw custom exception instead of build in one.
